services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped
  postgres-jerry:
    image: postgres:latest
    container_name: postgres-jerry
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_jerry
    ports:
      - "5433:5432"
    volumes:
      - pgdata-jerry:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped
  mail-dev:
    image: maildev/maildev:latest
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgdata-jerry:
    driver: local