spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: 192.168.1.11:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
topic:
  order:
    created: ORDER_CREATE_TOPIC
    cancelled: order-cancelled
    completed: order-completed
